version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
    volumes:
      - ~/.docker-conf/redis/data:/data
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_event_booking
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  ticket-service:
    build:
      context: ./ticket-service
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    networks:
      - my-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_event_booking
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  booking-service:
    build:
      context: ./booking-service
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    networks:
      - my-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_event_booking
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  event-service:
    build:
      context: ./event-service
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    networks:
      - my-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_event_booking
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  payment-service:
    build:
      context: ./payment-service
      dockerfile: ./Dockerfile
    ports:
      - "8085:8085"
    networks:
      - my-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_event_booking
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - AUTH_SERVICE_URL=http://user-service:8081
      - EVENT_SERVICE_URL=http://event-service:8082
      - TICKET_SERVICE_URL=http://ticket-service:8083
      - BOOKING_SERVICE_URL=http://booking-service:8084
      - PAYMENT_SERVICE_URL=http://payment-service:8085
    depends_on:
      user-service:
        condition: service_started
      event-service:
        condition: service_started
      ticket-service:
        condition: service_started
      booking-service:
        condition: service_started
      payment-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 10s
      retries: 15

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
