version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    networks:
      - my-network

  event-service:
    build:
      context: ./event-service
    ports:
      - "8082:8082"
    networks:
      - my-network

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - user-service
      - event-service

networks:
  my-network:
    driver: bridge
