version: '3.4'

services:
  ecommercestore:
    image: ecommercestore
    build:
      context: user-service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8081:8081
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
