version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_even_booking

  event-service:
    build:
      context: ./event-service
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    networks:
      - my-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_even_booking

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - AUTH_SERVICE_URL=http://user-service:8081
      - EVENT_SERVICE_URL=http://event-service:8082
    depends_on:
      - user-service
      - event-service

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongo-data:/data/db

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data: