# ticket-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
      - name: ticket-service
        image: booking-app/ticket-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/db_event_booking"
        - name: RABBITMQ_URL
          value: "amqp://user:password@rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: ticket-service