# user-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: booking-app/user-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/db_event_booking"
        - name: RABBITMQ_URL
          value: "amqp://user:password@rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: user-service