apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: event-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_SERVICE_URL
          value: "http://user-service:8081"
        - name: EVENT_SERVICE_URL
          value: "http://event-service:8082"
        - name: TICKET_SERVICE_URL
          value: "http://ticket-service:8083"
        - name: BOOKING_SERVICE_URL
          value: "http://booking-service:8084"

