apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: event-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/db_event_booking"
        - name: RABBITMQ_URL
          value: "amqp://user:password@rabbitmq:5672"